package com.isaaclyman.humanbingo

class PeopleSquares {
    val squares: List<String> = listOf(
            "Long beard",
            "Cell phone argument",
            "Stiletto heels",
            "Military uniform",
            "Bags under eyes",
            "Family with 3+ kids",
            "Asians with camera",
            "Cowboy hat & boots",
            "Neon-colored hair",
            "Man in a tank-top",
            // 10
            "Purple shoes",
            "Couple kissing",
            "Pregnant woman",
            "Age-inappropriate clothing",
            "Beret or fedora",
            "Screaming baby",
            "Drinking coffee",
            "Barefoot",
            "Bowtie",
            "Headphones too loud",
            // 20
            "College athlete",
            "Professional basketball fan",
            "Floral-print pants",
            "Booty shorts",
            "Shoulder-length earrings",
            "Man with a ponytail",
            "Dreadlocks",
            "Oxygen tank",
            "Traditional religious clothing",
            "Spray tan",
            // 30
            "Overstuffed backpack or luggage",
            "Bluetooth earpiece",
            "Socks and sandals",
            "Eating on the go",
            "Redhead",
            "Obviously in a hurry",
            "Not-so-subtle gum chewer",
            "Searching bag for lost item",
            "European accent",
            "Formally dressed",
            // 40
            "Belly hanging out",
            "Caveman eyebrows",
            "Drop-dead gorgeous",
            "Hair down to waist",
            "Needs a belt",
            "Visible bra straps",
            "Bright pink fingernail polish",
            "Hairy-bear legs",
            "Seeing-eye dog",
            "Obviously lost",
            // 50
            "Mismatched socks",
            "Pajamas",
            "Unsupervised child",
            "Video gamer",
            "Two visible tattoos",
            "Very muscular",
            "Timberlake lookalike",
            "Skinny as a rail",
            "Dressed in all black",
            "Smiling for no reason",
            // 60
            "Bed head",
            "Do-rag",
            "Cane",
            "Arm covered in bracelets",
            "Looking around nervously",
            "Wheelchair",
            "Gold watch",
            "His/her chain hangs low",
            "Energy drink",
            "Head partially shaved",
            // 70
            "Man bun",
            "Ironic T-shirt",
            "Shorts and tall socks",
            "Thick glasses",
            "Probably shops at Hot Topic",
            "Large drink",
            "Christian cross",
            "Working on the go",
            "Superhero fan",
            "Crying in public",
            // 80
            "Double stroller",
            "Cast or sling",
            "Disobeying a posted sign",
            "Shared headphones",
            "Odd couple",
            "Pant legs rolled up",
            "Accidental collision",
            "Sunburn",
            "Animal lover",
            "Frosted tips"
            // 90
    )
}